---
title: "事件研究法-宗族思想"
author: "小咩"
date: "2024-03-14"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = ".")
```


```{r 加载需要的包}
library(showtext)
showtext_auto()
library(patchwork)
library(dplyr)
```


```{r 读取数据}
data <- read.csv("caste.csv")
data
```


```{r}
data <- read.csv("caste.csv")

data$分类 <- factor(data$分类, levels = c("高种姓", "低种姓"))
data$受教育程度 <- factor(data$受教育程度, levels = c("高受教育程度", "平均受教育程度"))

data$parm <- factor(data$parm, levels = c("T_4", "T_3", "T_2", "T_1", "T0", "T1", "T2", "T3", "T4", "T5", "T6", "T7", "T8"))

p1 <- ggplot(filter(data, 受教育程度 == "高受教育程度"), aes(x = parm, y = estimate, group = 分类)) +
  geom_line(color = "black", position = position_dodge(width = 0.5)) +
  geom_point(position = position_dodge(width = 0.5), size = 1.5, shape = 21, fill = "black") +
  geom_errorbar(aes(ymin = min90, ymax = max90), width = 0.2, position = position_dodge(width = 0.5)) +
  scale_x_discrete(labels = c("-4期", "  ", "-2期", "  ", "0期", " ", "2期", " ", "4期", " ", "6期", " ", "8期")) +
  xlab("事件时间") + ylab("回归系数") +
  theme_grey(base_family = "STKaiti") +
  theme_classic() +
  geom_hline(yintercept = 0, linetype = "dashed", color = "grey") +
  facet_grid(受教育程度 ~ 分类, scales = "free_y")  # 根据分类变量分面，y轴自由缩放

p2 <- ggplot(filter(data, 受教育程度 == "平均受教育程度"), aes(x = parm, y = estimate, group = 分类)) +
  geom_line(color = "black", position = position_dodge(width = 0.5)) +
  geom_point(position = position_dodge(width = 0.5), size = 1.5, shape = 21, fill = "black") +
  geom_errorbar(aes(ymin = min90, ymax = max90), width = 0.2, position = position_dodge(width = 0.5)) +
  scale_x_discrete(labels = c("-4期", "  ", "-2期", "  ", "0期", " ", "2期", " ", "4期", " ", "6期", " ", "8期")) +
  xlab("事件时间") + ylab("回归系数") +
  theme_grey(base_family = "STKaiti") +
  theme_classic() +
  geom_hline(yintercept = 0, linetype = "dashed", color = "grey") +
  facet_grid(受教育程度~ 分类, scales = "free_y")  # 根据分类变量分面，y轴自由缩放


p1
p2
```




