---
title: "事件研究法-整体样本"
author: "小咩"
date: "2024-03-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r 加载需要的包}
library(showtext)
showtext_auto()
library(patchwork)
library(dplyr)
```


```{r 读取数据}
all <- read.csv("/Users/yuan/study/毕业论文- R绘图/事件研究法/印度/母职惩罚可视化/all_india.csv")
UR <- read.csv("/Users/yuan/study/毕业论文- R绘图/事件研究法/印度/母职惩罚可视化/UR_india.csv")
all
UR
```

```{r 整体样本}
all$parm <- factor(all$parm , levels = c("T_4", "T_3", "T_2","T_1", "T0", "T1", "T2", "T3", "T4	" ))

# 绘制图形，并指定纵坐标轴的范围
p <- ggplot(all, aes(x = parm, y = estimate, group = 分类)) +
  geom_line(color = "black", position = position_dodge(width = 0.5)) +
  geom_point(position = position_dodge(width = 0.5), size = 1.5, shape = 21, fill = "black") +
  geom_errorbar(aes(ymin = min90, ymax = max90), width = 0.2, position = position_dodge(width = 0.5)) +
  scale_x_discrete(labels = c("事前4期", "事前3期 ", "事前2期", " 事前1期", "事后0期", " 事后1期", "事后2期", "事后3期 ", "事后4期 ")) +
  xlab("事件时间") + ylab("回归系数") +
  theme_grey(base_family = "STKaiti") +
  theme_classic() +
  geom_hline(yintercept = 0, linetype = "dashed", color = "grey") 
p

```

```{r}
UR
```


```{r}
UR$parm <- factor(UR$parm , levels = c("T_4", "T_3", "T_2","T_1", "T0", "T1", "T2", "T3", "T4	" ))

UR$分类 <- factor(UR$分类, levels = c("城镇", "乡村"))

# 绘制图形，并指定纵坐标轴的范围
p <- ggplot(UR, aes(x = parm, y = estimate, group = 分类)) +
  geom_line(color = "black", position = position_dodge(width = 0.5)) +
  geom_point(position = position_dodge(width = 0.5), size = 1.5, shape = 21, fill = "black") +
  geom_errorbar(aes(ymin = min90, ymax = max90), width = 0.2, position = position_dodge(width = 0.5)) +
  scale_x_discrete(labels = c("事前4期", "事前3期 ", "事前2期", " 事前1期", "事后0期", " 事后1期", "事后2期", "事后3期 ", "事后4期 ")) +
  xlab("事件时间") + ylab("回归系数") +
  theme_grey(base_family = "STKaiti") +
  theme_classic() +
  geom_hline(yintercept = 0, linetype = "dashed", color = "grey") +
  facet_grid(~ 分类, scales = "free_y")

p

```


